language: rust
rust:
  - 1.32.0
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cd "${TRAVIS_BUILD_DIR}/schemars"
  - cargo check --verbose --no-default-features
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features --no-fail-fast
