language: rust
rust:
  - 1.32.0
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo check --verbose --all --no-default-features
  - cargo build --verbose --all --all-features
  - cargo test --verbose --all --all-features --no-fail-fast
