[package]
name = "schemars_derive"
description = "Macros for #[derive(JsonSchema)], for use with schemars"
repository = "https://github.com/GREsau/schemars"
version = "0.1.7"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"
license = "MIT"
keywords = ["rust", "json-schema", "serde"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6.13"
syn = { version = "0.15.44", features = ["extra-traits"] }
serde_derive_internals = "0.24.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
