[package]
name = "schemars_derive"
description = "Macros for #[derive(MakeSchema)], for use with schemars"
repository = "https://github.com/GREsau/schemars"
version = "0.1.0"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"
license = "MIT"
keywords = ["rust", "json-schema", "serde"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6.13"
syn = "0.15.22"
serde_derive_internals = "0.24.1"
