[package]
name = "schemars_derive"
version = "0.1.0"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6.13"
syn = "0.15.22"
serde_derive_internals = "0.24.1"
