[package]
name = "schemars"
description = "Generate JSON Schemas from Rust code"
repository = "https://github.com/GREsau/schemars"
version = "0.3.0"
authors = ["Graham Esau <gesau@hotmail.co.uk>"]
edition = "2018"
license = "MIT"
keywords = ["rust", "json-schema", "serde"]

[dependencies]
schemars_derive = { version = "0.3.0", path = "../schemars_derive" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", default-features = false, optional = true }

[dev-dependencies]
pretty_assertions = "0.6.1"

[[test]]
name = "chrono"
required-features = ["chrono"]

[package.metadata.docs.rs]
all-features = true
