name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.32.0
          - stable
          - beta
          - nightly
        include:
          - rust: 1.32.0
            test_features: "--features impl_json_schema,chrono,indexmap,either,uuid"
          - rust: stable
            test_features: "--all-features"
          - rust: beta
            test_features: "--all-features"
          - rust: nightly
            test_features: "--all-features"
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Check with no feature flags
        run: cargo check --verbose --no-default-features
        working-directory: ./schemars
      - name: Run tests
        run: cargo test --verbose ${{ matrix.test_features }} --no-fail-fast
        working-directory: ./schemars
      - name: Run derive tests
        run: cargo test --verbose --all-features --no-fail-fast
        working-directory: ./schemars_derive
